#!/usr/bin/env bash
# configure a Ubuntu machine so that '/redirect_me' is redirecting to another page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
REDIRECT="
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}"
sed -i "37i\ $REDIRECT" /etc/nginx/sites-available/default
service nginx restart
