#!/usr/bin/env bash
# configure a Ubuntu machine so that '/redirect_me' is redirecting to another page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
REDIRECT="server {
	listen 80;
	listen [::]:80 default_server;
	root   /var/www/html;
	index  index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}"
echo "$REDIRECT" >> /etc/nginx/sites-available/default
service nginx restart
