#!/usr/bin/env bash
# configure a Ubuntu machine so that '/redirect_me' is redirecting to another page
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /etc/nginx/html/index.html
REDIRECT="
	listen 80;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}\n"
sed -i "/server {/a $REDIRECT}" /etc/nginx/sites-available/default
service nginx restart
