#!/usr/bin/env bash
# configure Nginx server to have custom 404 page that contains "Ceci n'est pas une page"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
REDIRECT="server {
	listen 80;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	error_page 404 /404.html;
	location = /404.html {
		root /etc/nginx/html;
		internal;
	}
}"
echo "$REDIRECT" >> /etc/nginx/sites-available/default
service nginx restart
