#!/usr/bin/env bash
# configure ubuntu machine
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" | tee /var/www/html/404.html
print %s "server {
	listen 80 default_server;
        listen [::]:80 default_server;

	root /var/www/html;

	index index.html;

	add_header X-Served-By $HOSTNAME;
	location /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /404.html;
	location /404.html {
		internal;
	}
}" | tee /etc/nginx/sites-available/default
service nginx restart
