#!/usr/bin/env bash
# install and configure HAproxy
apt-get update
apt-get -y install haproxy
string="
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
backend web-backend
	balance roundrobin
	server 255371-web-01 100.25.33.231:80 check
	server 255371-web-02 54.237.87.188:80 check
"
echo "$string" | tee -a /etc/haproxy/haproxy.cfg
sed -i "s/ENABLED=0/ENABLED=1/" | tee -a /etc/default/haproxy
service haproxy restart
