#!/usr/bin/env bash
# install and configure HAproxy
apt-get update
apt-get -y install haproxy
string="
frontend modli-frontend
	bind *:80
	mode http
	default_backend mondli-backend
backend mondli-backend
	balance roundrobin
	server 255371-web-01 54.237.87.188:80 check
	server 255371-web-02 54.162.44.53:80 check
"
echo "$string" | tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | tee -a /etc/default/haproxy
service haproxy restart
