#!/usr/bin/env bash
# configure a server to run and listen on port 80 of all the server's active IPv4 IPs
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
