#!/usr/bin/env bash
# manage 'manage_my_process'

if [ ${1} == "start" ]; then
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ ${1} == "stop" ]; then
	echo "manage_my_process stopped"
	kill $(cat /var/run/my_process.pid)
	rm /var/run/my_process.pid
elif [ ${1} == "restart" ]; then
	kill $(cat /var/run/my_process.pid)
	rm /var/run/my_process.pid
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
