#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
#	display hours from 0 to 12
#	display minutes from 1 to 59
min=1
hour=0
while [ $hour -le 12 ]; do
	if [ $min -eq 1 ]; then
		echo "Hour: $hour"
		hour=$((hour + 1))
	fi
	echo "$min"
	min=$((min + 1))
	if [ $min -eq 60 ]; then
		min=1
	fi
done
