#!/usr/bin/env bash
# displays:
#	The content of the current directory
#	In a list format
#	Where only the part of the name after the first dash is displayed

for file in *; do
	if [ -f "$file" ]; then
		name=$(basename "$file")
		echo "$name" | cut -d'-' -f2
	fi
done
